config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home", page: "home"
  
  get "/static_pages/page", to: "static_pages#home"

  get "/signup", to: "users#new"
  post "/signup",  to: "users#create"
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

  get "/edit", to: "users#edit"
  post "/update", to: "users#update"

  delete "/logout", to: "sessions#destroy"
  
  resources :users, except: [:new, :destroy]
  resources :users do
    get "/:relationship", on: :member,
      to: "relationships#index", as: :relationships
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :requests, exept: [:new]
  
  resources :books, only: [:index, :show] do
    resources :reviews, except: :index do
      resources :comments, only: [:create, :update, :destroy]
    end
    resources :reading_statuses, only: [:create, :update]
  end

  namespace :admin do
    resources :categories, except: :show
    resources :books
    resources :requests, only: [:index, :destroy]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category

  has_many :reviews, dependent: :destroy
  has_many :reading_statuses, dependent: :destroy
  has_many :favorites, dependent: :destroy

  mount_uploader :cover, CoverUploader

  validates :title, presence: true, length: {maximum: 50}
  validates :author_name, presence: true, length: {maximum: 50}
  validates :pages, presence: true
  validates :publish_date, presence: true

  scope :order_by_time, -> {order created_at: :desc}
  scope :order_by_id, -> {order id: :desc}
  scope :search_book_by_search_params, -> search {
    where "title LIKE ? OR author_name LIKE ?",
      "%#{search}%", "%#{search}%" if search.present?}
  scope :by_category, -> category_id {
    where :category_id => category_id if category_id.present?}
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :verify_admin, except: :show
  before_action :find_book, except: [:index, :new, :create]
  before_action :load_categories, except: :index

  def index
    @categories = Category.all
    @books = Book.by_category(params[:category])
      .search_book_by_search_params(params[:search])
      .order_by_time
      .paginate page: params[:page], per_page: Settings.per_page
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new book_params
    if @book.save
      flash[:success] = t "admin.book.success"
      redirect_to admin_books_path
    else
      render :new
    end
  end

  def show
    @book = Book.find_by id: params[:id]
  end

  def edit
  end
  
  def update
    if @book.update_attributes book_params
      flash[:success] = t "admin.book.success_update"
      redirect_to admin_book_path
    else
      render :edit
    end
  end

  def destroy
    if @book.destroy
      flash[:success] = t "flash.destroy_success"
    else
      flash[:danger] = t "flash.destroy_error"
    end
    redirect_to admin_books_url
  end

  private
  def book_params
    params.require(:book).permit :category_id, :title, :author_name,
      :pages, :publish_date, :cover, :description
  end

  def find_book
    @book = Book.find_by id: params[:id]
    unless @book
      flash[:warning] = t "admin.book.not_find"
      redirect_to root_url
    end
  end

  def load_categories
    @categories = Category.all
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :logged_in_user

  def index
    @categories = Category.all
    @books = Book.by_category(params[:category])
      .search_book_by_search_params(params[:search])
      .order_by_time
      .paginate page: params[:page], per_page: Settings.per_page
  end

  def show
    @book = Book.find_by id: params[:id]
    unless @book
      flash[:warning] = t "admin.book.not_find"
      redirect_to root_url
    end
    @support = Supports::BookSupport.new @book
  end
end

app/views/admin/books/_book.html.erb
<table class="table table-hover">
  <tr>
    <th><%= t "admin.book.bood_id" %></th>
    <th><%= t "admin.book.cover" %></th>
    <th><%= t "admin.book.title" %></th>
    <th><%= t "admin.book.author_name" %></th>
    <th><%= t "admin.book.pages" %></th>
    <th><%= t "admin.book.publish_date" %></th>
    <th><%= t "admin.book.active" %></th>
  </tr>
  <% @books.each do |book| %>
    <tr>
      <td><%= book.id %></td>
      <td>
        <%= link_to image_tag(book.cover.url), admin_book_path(book),
          class: "img-responsive" if book.cover? %>
      </td>
      <td><%= book.title %></td>
      <td><%= book.author_name %></td>
      <td><%= book.pages %></td>
      <td><%= book.publish_date %></td>
      <td>
        <span>
          <%= link_to t("admin.book.edit_button"), edit_admin_book_url(book),
          class: "btn btn-info" %>
          <%= link_to t("admin.book.delete_button"), admin_book_url(book),
          method: :delete, data: {confirm: t("admin.book.delete_confirm")},
          class: "btn btn-danger" %>
        </span>
      </td>
    </tr>
  <% end %>
</table>

app/views/admin/books/_form.html.erb
<%= form_for [:admin, @book], html: {multipart: true} do |f| %>
  <%= render "shared/error_messages", object: @book %>

  <%= f.label :category %>
  <%= f.select :category_id , options_for_select(@categories.collect{|c| [c.name, c.id]}) %>    

  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :author_name %>
  <%= f.text_field :author_name, class: "form-control" %>

  <%= f.label :pages %>
  <%= f.number_field :pages, class: "form-control" %>

  <%= f.label :publish_date %>
  <%= f.date_field :publish_date, class: "form-control" %>

  <%= f.label :cover %>
  <%= f.file_field :cover, accept: "image/jpeg,image/gif,image/png" %>

  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/books/_search_form.html.erb
<%= form_tag admin_books_path, method: :get do %>
  <div class= "col-md-4">
    <%= text_field_tag :search, params[:search], class: "search-form",
      placeholder: t("book.search_book") %>
  </div>
  <div class= "col-md-4">
    <%= select_tag t("book.category"),
      options_for_select(@categories.map{|f| [f.name, f.id]}),
      class: "select", include_blank: t("book.all") %> 
  </div>
  <div class= "col-md-2">
    <%= submit_tag t "book.search", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/admin/books/edit.html.erb
<h1><%= t "admin.book.heading_edit" %></h1>
<% provide :button_text, t("admin.book.edit_book") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/books/index.html.erb
<h1><%= t "admin.book.dashboard" %></h1>
<%= render "search_form" %>
<div class="books"><%= render "book" %></div>
<%= link_to t("admin.book.new_book"), new_admin_book_path,
  class: "btn btn-info" %>

app/views/admin/books/new.html.erb
<h2><%= t "admin.book.create_book" %></h2>
<%= form_for @book, url: admin_books_path, html: {multipart: true} do |f| %>
  <%= render partial: "shared/error_messages", locals: {object: @book} %>

  <%= f.label :category %>
  <%= f.select :category_id , @categories.collect{|c| [c.name, c.id]} %>    

  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :author_name %>
  <%= f.text_field :author_name, class: "form-control" %>

  <%= f.label :pages %>
  <%= f.number_field :pages, class: "form-control" %>

  <%= f.label :publish_date %>
  <%= f.date_field :publish_date, class: "form-control" %>

  <%= f.label :cover %>
  <%= f.file_field :cover, accept: "image/jpeg,image/gif,image/png" %>

  <%= f.label :description %>
  <%= f.text_field :description, class: "form-control" %>

  <%= f.submit t("admin.book.create_book"), class: "btn btn-primary" %>
<% end %>

app/views/admin/books/show.html.erb
<h1><%= t "admin.book.dashboard" %></h1>
  <div class="panel panel-default">
    <div class="book-details">
      <div class="col-sm-3">
        <div class="view-book">
          <%= image_tag @book.cover.url if @book.cover? %>
        </div>
      </div>
      <div class="col-sm-9">
        <div class="book-information">
          <h3><%= @book.title %></h3>
          <p>
            <%= t "admin.book.show_author" %>
            <%= @book.author_name %>
          </p>
          <p>
            <b><%= t "admin.book.publishdate" %></b>
            <%= @book.publish_date %>
          </p>
          <p>
            <b><%= t "admin.book.pages" %></b>
            <%= @book.pages %>
          </p>
          <p>
            <b><%= t "admin.book.show_category" %></b>
            <%= @book.category.name %>
          </p>
          <p>
            <b><%= t "admin.book.description" %></b>
            <%= @book.description %>
          </p>
        </div>
      </div>
    </div>
      <span>
        <%= link_to t("admin.book.edit_button"), edit_admin_book_url(@book),
          class: "btn btn-info" %>
        <%= link_to t("admin.book.delete_button"), admin_book_url(@book),
          method: :delete, data: {confirm: t("admin.book.delete_confirm")},
          class: "btn btn-danger" %>
        <%= link_to t("admin.book.back_button"), admin_books_path,
          class: "btn btn-warning" %>
      </span>
  </div>
<%= link_to t("admin.book.new_book"), new_admin_book_path %>