config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home", page: "home"
  
  get "/static_pages/page", to: "static_pages#home"

  get "/signup", to: "users#new"
  post "/signup",  to: "users#create"
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

  get "/edit", to: "users#edit"
  post "/update", to: "users#update"

  delete "/logout", to: "sessions#destroy"
  
  resources :users, except: [:new, :destroy]
  resources :users do
    get "/:relationship", on: :member,
      to: "relationships#index", as: :relationships
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :requests, exept: [:new]
  
  resources :books, only: [:index, :show] do
    resources :reviews, except: :index do
      resources :comments, only: [:create, :update, :destroy]
    end
    resources :reading_statuses, only: [:create, :update]
  end

  namespace :admin do
    resources :categories, except: :show
    resources :books
    resources :requests, only: [:index, :destroy]
  end
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "shared.error_message" %>
      <%= pluralize object.errors.count, t("shared.error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <%= link_to relationships_user_path @user, relationship: "following" do %>
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    <%= t "shared.following" %>
  <% end %>
  <%= link_to relationships_user_path @user, relationship: "followers" do %>
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
     <%= t "shared.followers" %>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t("shared.view_profile"), current_user %></span>