config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home", page: "home"
  
  get "/static_pages/page", to: "static_pages#home"

  get "/signup", to: "users#new"
  post "/signup",  to: "users#create"
  
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"

  get "/edit", to: "users#edit"
  post "/update", to: "users#update"

  delete "/logout", to: "sessions#destroy"
  
  resources :users, except: [:new, :destroy]
  resources :users do
    get "/:relationship", on: :member,
      to: "relationships#index", as: :relationships
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :requests, exept: [:new]
  
  resources :books, only: [:index, :show] do
    resources :reviews, except: :index do
      resources :comments, only: [:create, :update, :destroy]
    end
    resources :reading_statuses, only: [:create, :update]
  end

  namespace :admin do
    resources :categories, except: :show
    resources :books
    resources :requests, only: [:index, :destroy]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books

  validates :name, presence: true, length: {maximum: 30}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  
  before_action :verify_admin
  before_action :find_category, except: [:index, :new, :create]

  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t "flash.success_category"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t "flash.update_category"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t "flash.destroy_category_success"
    else
      flash[:danger] = t "flash.destroy_category_error"
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name, :description
  end

  def find_category
    @category = Category.find_by id: params[:id]
    unless @category
      flash[:warning] = t "flash.error_find_catagory"
      redirect_to admin_categories_path	
    end
  end
end

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: @category %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :description %>
  <%= f.text_area :description, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/admin/categories/edit.html.erb
<h1><%= t "admin.category.heading_edit" %></h1>
<% provide :button_text, t("admin.category.edit_category") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<h1><%= t "admin.category.dashboard" %></h1>
<table class="table table-hover">
  <tr>
    <th><%= t "admin.category.category_id" %></th>
    <th><%= t "admin.category.name" %></th>
    <th><%= t "admin.category.description" %></th>
    <th><%= t "admin.category.active" %></th>
  </tr>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.id %></td>
      <td><%= category.name %></td>
      <td><%= category.description %></td>
      <td>
        <span>
          <%= link_to t("admin.book.edit_button"), edit_admin_category_url(category),
            class: "btn btn-info" %>
          <%= link_to t("admin.book.delete_button"), admin_category_url(category),
            method: :delete, data: {confirm: t("admin.book.delete_confirm")},
              class: "btn btn-danger" %>
        </span>
      </td>
    </tr>
  <% end %>
</table>
<%= link_to t("admin.category.new_category"), new_admin_category_path,
  class: "btn btn-info" %>

app/views/admin/categories/new.html.erb
<h2><%= t "admin.category.create_category" %></h2>
<% provide :button_text, t("admin.category.create_category") %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>